# Generated by Django 5.2.1 on 2025-06-20 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('stock', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categoria.categoria')),
            ],
        ),
    ]
