# Generated by Django 5.2.1 on 2025-06-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.PositiveIntegerField(unique=True)),
                ('apellidos', models.CharField(max_length=80)),
                ('nombres', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
