# Generated by Django 5.2.1 on 2025-06-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.PositiveIntegerField(unique=True)),
                ('apellidos', models.CharField(max_length=80)),
                ('nombres', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
